server:
  port: 9300

spring:
  application:
    name: yem-gateway

#--------------------eureka---------------------
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:9900/eureka/
#--------------------Zuul-----------------------
zuul:
  routes:
    member:
      path: /yem/v1/**
      serviceId: yem-base
      sensitiveHeaders: "*"
    base:
      path: /yem/v1/**
      serviceId: yem-member
      sensitiveHeaders: "*"
    auth:
      path: /yem/auth/**
      serviceId: yem-auth
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  add-proxy-headers: true


#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/yem/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/yem/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/yem/auth/user
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 6000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000